# Generated by Django 4.2.4 on 2023-10-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_myuser_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='active',
            new_name='email_active',
        ),
    ]
