# Generated by Django 4.2.6 on 2023-10-26 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_active_myuser_email_active'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sum_rate',
        ),
        migrations.AddField(
            model_name='post',
            name='avg_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='nor',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.myuser')),
            ],
        ),
    ]
